### ISSUE TITLE
Use encrypted bucket module from cloud.gov

### ISSUE THREAD

**Issue by Vermyndax** [GSA/DevSecOps-Mgmt-Tools-Deploy#8]
I'd like to use: https://github.com/18F/cg-provision/blob/master/terraform/modules/s3_bucket/encrypted_bucket/encrypted_bucket.tf
...for the S3 bucket to back up jenkins, but setting up a policy that forces encryption could lead to a situation that runs afoul of GSA security's KMS key requirements. Anyone have an opinion on guidance for this one?

**Comment by afeld** [comment]
@eyard @kishorebabu12 ^

**Comment by tim20watts** [comment]
Jason The Cloud team has some extensive working knowledge on this subject.
you may want to reach out to Julius Williams - IOH <julius.williams@gsa.gov>
Or my self <timothy.watts@gsa.gov> and we mably to help.

Thank you in advance,
Timothy E. Watts - IDIHC
Cloud Management Branch - Innovation Specialist
Office (504) 249-6438 | Cell (985) 237-0782 | timothy.watts@gsa.gov |
www.gsa.gov

*CONTACT US:*
Reach the Cloud Management Branch on our "Chatter Page"!
Email Cloud Management Branch at "cloudmgmt@gsa.gov".

**Comment by Vermyndax** [comment]
This is implemented here: https://github.com/GSA/devsecops-example-pipeline/pull/2
